include: 
  - "https://raw.githubusercontent.com/kinhnv/Platform.Common/main/pipeline/.prepare-ssh.yml"
  - "https://raw.githubusercontent.com/kinhnv/Platform.Common/main/pipeline/.dotnet.yml"

stages:
  - build
  - test
  - deploy

.production_config:
  variables:
    ASPNETCORE_ENVIRONMENT: "Production"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

.deploy_tags:
  tags:
    - "shell"
  
build:
  stage: build
  variables:
    VERSION: ${CI_PIPELINE_ID}
    DOCKERFILE: ${CI_PROJECT_DIR}/ApiGateway/Dockerfile
    IMAGE: registry.gitlab.com/i3rothers/common/api-gateway:${CI_PIPELINE_ID}
  extends:
    - .production_config
    - .dotnet_build

test:
  stage: test
  tags:
    - "test"
  extends:
    - .production_config
  script:
    - echo "test"

deploy:
  stage: deploy
  variables:
    VERSION: ${CI_PIPELINE_ID}
    TAG_CONFIG: .servers.apiGateway.tag
    VALUE_YAML_FILE: common/values.yaml
  extends:
    - .production_config
    - .dotnet_deploy